name: Tests

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
